---
groups:
- name: build-pipeline
  jobs:
  - node-build
  - deploy-to-dev
  - run-health-check
  - run-functional-check
  - deploy-to-staging
  # - run-e2e-test
  # - validate-test-result
  - deploy-to-production
  - promote-new-version
  # - upload-git-release

- name: init-dynatrace
  jobs: 
  - init-dynatrace-front-end

- name: performance
  jobs:
  - run-performance-check
  - validate-performance-check

resource_types:
- name: dynatrace-resource
  type: docker-image
  source:
    repository: mvilliger/dynatrace-resource

resources:

#GitHub Release Repository
# - name: front-end-release
#   type: github-release
#   source:
#     owner: acm-workshop-concourse
#     repository: front-end
#     access_token: ((github-access-token))

# GitHub Repositories
- name: git-pipeline
  type: git
  source:
    branch: master
    uri: https://github.com/((pipeline-tasks))/cf-deploy-sockshop.git

- name: git-front-end
  type: git
  source:
    branch: master
    uri: https://github.com/((source-code))/front-end.git

- name: dynatrace
  type: dynatrace-resource
  source:
    apitoken: ((dt_api_token))
    tenanthost: ((dt_tenant_host))

- name: front-end-release-bucket
  type: s3
  source:
    region_name: eu-west-1
    regexp: front-end/front-end-(.*).tar
    bucket: ((s3-bucket))
    access_key_id: ((s3-access-key-id))
    secret_access_key: ((s3-secret-access-key))

- name: version
  type: semver
  source:
    driver: git
    uri: https://github.com/((source-code))/front-end.git
    branch: master
    file: version

# PCF Environments

- name: pcf-dev
  type: cf
  source:
    api: ((pcf-dev-api))
    username: ((pcf-username))
    password: ((pcf-password))
    organization: ((pcf-dev-organization))
    space: ((pcf-dev-space))
    skip_cert_check: false

- name: pcf-staging
  type: cf
  source:
    api: ((pcf-staging-api))
    username: ((pcf-username))
    password: ((pcf-password))
    organization: ((pcf-staging-organization))
    space: ((pcf-staging-space))
    skip_cert_check: false

- name: pcf-production
  type: cf
  source:
    api: ((pcf-production-api))
    username: ((pcf-username))
    password: ((pcf-password))
    organization: ((pcf-production-organization))
    space: ((pcf-production-space))
    skip_cert_check: false

jobs:

# Initialize Dynatrace Custom Device

- name: init-dynatrace-front-end
  public: true
  plan:
  - aggregate:
    - get: git-pipeline
    - get: git-front-end 
  - task: init-dynatrace-task
    file: git-pipeline//ci/tasks/init-dynatrace-task.yml
    params: 
      apitoken: ((dt_api_token))
      tenanthost: ((dt_tenant_host))
      APP_REPO: git-front-end

# FRONT-END

- name: node-build
  plan:
  - get: git-front-end
    trigger: false
  - get: version
    params: { pre: build }
  - task: create-tarball
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: busybox}
      inputs:
      - name: git-front-end
      - name: version
      outputs:
      - name: workspace
      run:
        path: /bin/sh
        args:
        - -exc
        - |
          output_dir=workspace
          cp git-front-end/server.js "${output_dir}/"
          tar -cf "${output_dir}"/front-end-$(cat version/number).tar "${output_dir}"/server.js
  - put: front-end-release-bucket
    params: 
      file: workspace/front-end-*.tar

- name: deploy-to-dev
  serial: true
  public: true
  plan:
  - get: git-front-end
    trigger: true
    passed:
      - node-build
  - get: front-end-release-bucket
    passed:
      - node-build
  - get: git-pipeline
    trigger: false      
  - task: prepare-app-manifest
    file: git-pipeline//ci/tasks/app-manifest-prep.yml
    params:
      STAGE: Dev
      PCF_APP_SUFFIX: ((pcf-dev-front-end-suffix)) 
      APP_REPO: git-front-end           
  - put: pcf-dev
    params:
      path: git-front-end
      manifest: app-manifest-output/manifest.yml
  - put: dynatrace
    params:
      monspecserviceenvironment: front-end/Dev
      pipelinetaskname: deploy-to-dev
      deployversion: v1.0
      APP_REPO: git-front-end

- name: run-health-check
  serial: true
  public: true
  plan:
  - aggregate:
    - get: git-front-end
      trigger: true
      passed:
        - deploy-to-dev
    - get: git-pipeline
      trigger: false 
  - task: run-health-check
    file: git-pipeline//ci/tasks/jmeter-test.yml
    params:
      APP_REPO: git-front-end
      PRODUCTION: false
      SCRIPT_NAME: jmeter/basiccheck.jmx
      RESULT_DIR: HealthCheck
      PCF_APP_SUFFIX: ((pcf-dev-front-end-suffix))
      PCF_APP_DOMAIN: ((pcf-dev-app-domain))
      CHECK_PATH: /health
      SERVER_PORT: 80
      VU_COUNT: 1
      LOOP_COUNT: 1
      DT_LTN: HealthCheck
      FUNC_VALIDATION: true
      THINK_TIME: 0

- name: run-functional-check
  serial: true
  public: true
  plan:
  - aggregate:
    - get: git-front-end
      trigger: true
      passed:
        - run-health-check
    - get: git-pipeline
  - task: run-functional-check
    file: git-pipeline//ci/tasks/jmeter-test.yml
    params:
      APP_REPO: git-front-end
      PRODUCTION: false
      SCRIPT_NAME: jmeter/front-end_load.jmx
      RESULT_DIR: FuncCheck
      PCF_APP_SUFFIX: ((pcf-dev-front-end-suffix))
      PCF_APP_DOMAIN: ((pcf-dev-app-domain))
      CHECK_PATH: /health
      SERVER_PORT: 80
      VU_COUNT: 1
      LOOP_COUNT: 1
      DT_LTN: FuncCheck
      FUNC_VALIDATION: true
      AVG_RT_VALIDATION: 3000
      THINK_TIME: 0

- name: deploy-to-staging
  serial: true
  public: true
  plan:
  - get: git-front-end
    trigger: true
    passed:
      - run-functional-check
  - get: front-end-release-bucket
    passed:
      - node-build
  - get: git-pipeline
    trigger: false      
  - task: prepare-app-manifest
    file: git-pipeline//ci/tasks/app-manifest-prep.yml
    params:
      STAGE: Staging
      PCF_APP_SUFFIX: ((pcf-staging-front-end-suffix)) 
      APP_REPO: git-front-end
  - put: pcf-staging
    params:
      path: git-front-end
      manifest: app-manifest-output/manifest.yml          
  - put: dynatrace
    params:
      monspecserviceenvironment: front-end/Staging
      pipelinetaskname: deploy-to-staging
      deployversion: v1.0 
      APP_REPO: git-front-end 

# - name: run-e2e-test
#   serial: true
#   public: true
#   plan:
#   - aggregate:
#     - get: git-front-end
#       trigger: true
#       passed:
#        - deploy-to-staging
#     - get: git-pipeline
#   - task: run-e2e-check
#     file: git-pipeline//ci/tasks/load-tests.yml
#     params:
#       APP_REPO: git-pipeline
#       FUNC_VALIDATION: yes
#       PRODUCTION: true
#       SCRIPT_NAME: /ci/jmeterfront-end_e2e_load.jmx
#       PCF_APP_SUFFIX: ((pcf-staging-front-end-suffix))
#       PCF_APP_DOMAIN: ((pcf-staging-app-domain))
#       DT_LTN: e2eCheck
#       VUCount: 5
#       LoopCount: 20 
#   - task: push-dynatrace-monspec-data
#     file: git-pipeline//ci/tasks/push-dynatrace-monspec-data.yml
#     params: 
#       monspecserviceenvironment: front-end/Production-$NEXT_APP_COLOR
#       apitoken: ((apitoken))
#       tenanthost: ((tenanthost))
#       APP_REPO: git-front-end 

# - name: validate-front-end-load-test
#   plan:
#   - get: git-front-end
#     trigger: true
#     passed:
#       - execute-front-end-load-tests
#   - get: git-pipeline
#     trigger: false      
#   - task: get-current-app-color
#     file: git-pipeline//ci/tasks/current-app-get-info.yml
#     params:
#       PCF_APP_SUFFIX: ((pcf-prod-front-end-suffix))
#       PCF_API: ((pcf-prod-api))
#       PCF_ORG: ((pcf-prod-organization))
#       PCF_USER: ((pcf-prod-deploy-username))
#       PCF_PWD: ((pcf-prod-deploy-password))
#       PCF_SPACE: ((pcf-prod-space))       
#   - task: validate-via-monspec
#     file: git-pipeline//ci/tasks/validate-via-monspec.yml
#     params: 
#       monspeccomparison: front-end/Production-$NEXT_APP_COLOR\ToProduction-$CURRENT_APP_COLOR\Last5m
#       apitoken: ((apitoken))
#       tenanthost: ((tenanthost))
#       APP_REPO: git-front-end  

- name: deploy-to-production
  serial: true
  public: true
  plan:
  - get: git-front-end
    trigger: true
    passed:
      - deploy-to-staging
  - get: front-end-release-bucket
    passed:
      - node-build
  - get: git-pipeline
    trigger: false      
  - task: get-current-app-color
    file: git-pipeline//ci/tasks/current-app-get-info.yml
    params:
      PCF_APP_SUFFIX: ((pcf-production-front-end-suffix))
      PCF_API: ((pcf-production-api))
      PCF_ORG: ((pcf-production-organization))
      PCF_SPACE: ((pcf-production-space))  
      PCF_USER: ((pcf-username))
      PCF_PWD: ((pcf-password))
  - task: prepare-app-manifest
    file: git-pipeline//ci/tasks/app-manifest-prep.yml
    params:
      STAGE: Production
      PCF_APP_SUFFIX: ((pcf-production-front-end-suffix)) 
      APP_REPO: git-front-end               
  - put: pcf-production
    params:
      path: git-front-end
      manifest: app-manifest-output/manifest.yml
  - put: dynatrace
    params:
      monspecserviceenvironment: front-end/Production
      pipelinetaskname: deploy-to-production
      deployversion: v1.0 
      APP_REPO: git-front-end 

- name: promote-new-version
  serial: true
  public: true
  plan:
  - get: git-front-end
    trigger: true
    passed:
      - deploy-to-production
  - get: git-pipeline
    trigger: false      
  - task: get-current-app-color
    file: git-pipeline//ci/tasks/current-app-get-info.yml
    params:
      PCF_APP_SUFFIX: ((pcf-production-front-end-suffix))
      PCF_API: ((pcf-production-api))
      PCF_ORG: ((pcf-production-organization))
      PCF_SPACE: ((pcf-production-space))  
      PCF_USER: ((pcf-username))
      PCF_PWD: ((pcf-password))
  - task: switch-app-routes
    file: git-pipeline//ci/tasks/update-routes.yml
    params:
      PCF_APP_SUFFIX: ((pcf-production-front-end-suffix))
      PCF_APP_DOMAIN: ((pcf-production-app-domain))
      PCF_API: ((pcf-production-api))
      PCF_ORG: ((pcf-production-organization))
      PCF_SPACE: ((pcf-production-space))
      PCF_USER: ((pcf-username))
      PCF_PWD: ((pcf-password))

# - name: upload-front-end-git-release
#   public: true
#   plan:
#   - aggregate:
#     - get: git-front-end
#       trigger: true
#       passed: 
#         - promote-new-version-front-end
#     - get: front-end-release-bucket
#     - get: git-pipeline
#     - get: version
#       params: { pre: build }
#   - task: create-front-end-release-info
#     file: git-pipeline//ci/tasks/prepare-release.yml
#     params:
#       APP_NAME: front-end
#   - put: front-end-release
#     params:
#       name: prepared-release/name
#       tag: prepared-release/tag
#      globs:
#      - front-end-release-bucket/front-end-*.jar
#  - put: version
#    params: { file: version/number }

- name: run-performance-check
  serial: true
  public: true
  plan:
  - aggregate:
    - get: git-front-end
      trigger: false
    - get: git-pipeline
  - task: run-performance-check
    file: git-pipeline//ci/tasks/jmeter-test.yml
    params:
      APP_REPO: git-front-end
      PRODUCTION: false
      SCRIPT_NAME: jmeter/front-end_load.jmx
      RESULT_DIR: PerfCheck
      PCF_APP_SUFFIX: ((pcf-dev-front-end-suffix))
      PCF_APP_DOMAIN: ((pcf-dev-app-domain))
      SERVER_PORT: 80
      VU_COUNT: 10
      LOOP_COUNT: 25 #250
      DT_LTN: FuncCheck
      FUNC_VALIDATION: false
      AVG_RT_VALIDATION: 3000
      THINK_TIME: 0
  - task: push-dynatrace-monspec-data
    file: git-pipeline//ci/tasks/push-dynatrace-monspec-data.yml
    params: 
      monspecserviceenvironment: front-end/Dev
      apitoken: ((dt_api_token))
      tenanthost: ((dt_tenant_host))
      APP_REPO: git-front-end 

- name: validate-performance-check
  serial: true
  public: true
  plan:
  - get: git-front-end
    trigger: true
    passed:
      - run-performance-check
  - get: git-pipeline
    trigger: false      
  - task: validate-via-monspec
    file: git-pipeline//ci/tasks/validate-via-monspec.yml
    params: 
      monspeccomparison: front-end/DevToDevLastHour
      apitoken: ((dt_api_token))
      tenanthost: ((dt_tenant_host))
      APP_REPO: git-front-end 